# CVE-2019-17498

## About
* <https://nvd.nist.gov/vuln/detail/CVE-2019-17498>

## Details
The source location of the vulnerability is [packet.c:480](https://github.com/libssh2/libssh2/blob/42d37aa63129a1b2644bf6495198923534322d64/src/packet.c#L480):

```c
if(message_len < datalen-13) {
```

The value of `datalen` is untrusted because it came from the remote computer. If `datalen == 11`, for example, then the subtraction will overflow and the bounds-check of `message_len` is ineffective, leading to an out-of-bounds read on [line 485](https://github.com/libssh2/libssh2/blob/42d37aa63129a1b2644bf6495198923534322d64/src/packet.c#L485).

## PoC / Exploit

* <https://github.com/kevinbackhouse/security-lab/tree/master/SecurityExploits/libssh2/out_of_bounds_read_disconnect_CVE-2019-17498> 


## Environment used

* Ubuntu 18.04.3 LTS


## Reproduction
* Terminal 1
```bash
bash server.sh
```
* Terminal 2
```bash
bash client.sh
cd ~/libssh2/example && ./ssh2 172.18.0.10
```
<br>
The result should be a message with <i>"Segmentation fault"</i>. This happens due to 
an error checking the message length. 
